import type { Task } from "./types";

export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Finish lab report",
    notes: "Organic chemistry lab — due Thursday",
    priority: "P0",
    estimateMinutes: 180,
    dueDate: "2026-03-26",
    status: "scheduled",
    timeBlockId: "block-4",
  },
  {
    id: "task-2",
    title: "Study for midterm",
    notes: "Chapters 7-12, focus on thermodynamics",
    priority: "P0",
    estimateMinutes: 480,
    dueDate: "2026-03-27",
    status: "scheduled",
    timeBlockId: "block-5",
  },
  {
    id: "task-3",
    title: "Gym — upper body",
    priority: "P1",
    estimateMinutes: 60,
    recurrenceRule: "MWF",
    status: "scheduled",
    timeBlockId: "block-7",
  },
  {
    id: "task-4",
    title: "Gym — cardio",
    priority: "P1",
    estimateMinutes: 60,
    recurrenceRule: "TTh",
    status: "unscheduled",
  },
  {
    id: "task-5",
    title: "Read chapter 13",
    notes: "Intro to Machine Learning textbook",
    priority: "P1",
    estimateMinutes: 90,
    status: "unscheduled",
  },
  {
    id: "task-6",
    title: "Submit club budget proposal",
    notes: "Robotics club — treasurer duties",
    priority: "P1",
    estimateMinutes: 45,
    dueDate: "2026-03-25",
    status: "unscheduled",
  },
  {
    id: "task-7",
    title: "Call home",
    priority: "P2",
    estimateMinutes: 30,
    status: "unscheduled",
  },
  {
    id: "task-8",
    title: "Grocery run",
    priority: "P2",
    estimateMinutes: 45,
    status: "unscheduled",
  },
  {
    id: "task-9",
    title: "Review lecture notes — Week 8",
    priority: "P1",
    estimateMinutes: 60,
    status: "done",
  },
  {
    id: "task-10",
    title: "Fix bike tire",
    priority: "P2",
    estimateMinutes: 30,
    status: "done",
  },
];
